BuildError
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?

Traceback (most recent call last)
File "C:\Python312\Lib\site-packages\flask\app.py", line 1478, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\app\utils\auth.py", line 146, in decorated_function
return f(*args, **kwargs)
       ^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\run.py", line 198, in gestor_ambientes
return render_template('Gestor/GerenciarAmbientes/ambiente.html',
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 152, in render_template
return _render(app, template, context)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 133, in _render
rv = template.render(context)
     ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 1304, in render
self.environment.handle_exception()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\GerenciarAmbientes\ambiente.html", line 26, in top-level template code
{% include 'Gestor/GerenciarAmbientes/modals.html' %}
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\GerenciarAmbientes\modals.html", line 16, in top-level template code
<li><a href="{{ url_for('reservas') }}" class="flex items-center p-3 text-gray-700 rounded-lg hover:bg-gray-100"><span class="ml-3">Reserva de Equipamentos</span></a></li>
File "C:\Python312\Lib\site-packages\flask\app.py", line 1071, in url_for
return self.handle_url_build_error(error, endpoint, values)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1060, in url_for
rv = url_adapter.build(  # type: ignore[union-attr]
     
File "C:\Python312\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
raise BuildError(endpoint, values, method, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.+




BuildError
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?

Traceback (most recent call last)
File "C:\Python312\Lib\site-packages\flask\app.py", line 1478, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\app\utils\auth.py", line 146, in decorated_function
return f(*args, **kwargs)
       ^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\run.py", line 235, in gestor_equipamentos_mobilizados
return render_template('Gestor/EquipamentosMobilizados/mobilizados.html',
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 152, in render_template
return _render(app, template, context)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 133, in _render
rv = template.render(context)
     ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 1304, in render
self.environment.handle_exception()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\EquipamentosMobilizados\mobilizados.html", line 26, in top-level template code
{% include 'Gestor/EquipamentosMobilizados/modals.html' %}
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\EquipamentosMobilizados\modals.html", line 16, in top-level template code
<li><a href="{{ url_for('reservas') }}" class="flex items-center p-3 text-gray-700 rounded-lg hover:bg-gray-100"><span class="ml-3">Reserva de Equipamentos</span></a></li>
File "C:\Python312\Lib\site-packages\flask\app.py", line 1071, in url_for
return self.handle_url_build_error(error, endpoint, values)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1060, in url_for
rv = url_adapter.build(  # type: ignore[union-attr]
     
File "C:\Python312\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
raise BuildError(endpoint, values, method, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.





BuildError
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?

Traceback (most recent call last)
File "C:\Python312\Lib\site-packages\flask\app.py", line 1478, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\app\utils\auth.py", line 146, in decorated_function
return f(*args, **kwargs)
       ^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\run.py", line 246, in gestor_equipamentos_imobilizados
return render_template('Gestor/EquipamentosImobilizados/imobilizados.html',
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 152, in render_template
return _render(app, template, context)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 133, in _render
rv = template.render(context)
     ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 1304, in render
self.environment.handle_exception()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\EquipamentosImobilizados\imobilizados.html", line 26, in top-level template code
{% include 'Gestor/EquipamentosImobilizados/modals.html' %}
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\EquipamentosImobilizados\modals.html", line 16, in top-level template code
<li><a href="{{ url_for('reservas') }}" class="flex items-center p-3 text-gray-700 rounded-lg hover:bg-gray-100"><span class="ml-3">Reserva de Equipamentos</span></a></li>
File "C:\Python312\Lib\site-packages\flask\app.py", line 1071, in url_for
return self.handle_url_build_error(error, endpoint, values)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1060, in url_for
rv = url_adapter.build(  # type: ignore[union-attr]
     
File "C:\Python312\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
raise BuildError(endpoint, values, method, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.


BuildError
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?

Traceback (most recent call last)
File "C:\Python312\Lib\site-packages\flask\app.py", line 1478, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\app\utils\auth.py", line 146, in decorated_function
return f(*args, **kwargs)
       ^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\run.py", line 284, in gestor_reservas
return render_template('Gestor/GerenciarReservas/reservas.html',
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 152, in render_template
return _render(app, template, context)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 133, in _render
rv = template.render(context)
     ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 1304, in render
self.environment.handle_exception()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\GerenciarReservas\reservas.html", line 25, in top-level template code
{% include 'Gestor/GerenciarReservas/modals.html' %}
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\GerenciarReservas\modals.html", line 16, in top-level template code
<li><a href="{{ url_for('reservas') }}" class="flex items-center p-3 text-gray-700 rounded-lg hover:bg-gray-100"><span class="ml-3">Reserva de Equipamentos</span></a></li>
File "C:\Python312\Lib\site-packages\flask\app.py", line 1071, in url_for
return self.handle_url_build_error(error, endpoint, values)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1060, in url_for
rv = url_adapter.build(  # type: ignore[union-attr]
     
File "C:\Python312\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
raise BuildError(endpoint, values, method, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.




BuildError
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?

Traceback (most recent call last)
File "C:\Python312\Lib\site-packages\flask\app.py", line 1478, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\app\utils\auth.py", line 146, in decorated_function
return f(*args, **kwargs)
       ^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\run.py", line 284, in gestor_reservas
return render_template('Gestor/GerenciarReservas/reservas.html',
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 152, in render_template
return _render(app, template, context)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\templating.py", line 133, in _render
rv = template.render(context)
     ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 1304, in render
self.environment.handle_exception()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\GerenciarReservas\reservas.html", line 25, in top-level template code
{% include 'Gestor/GerenciarReservas/modals.html' %}
File "C:\Users\Antonio50245186\Downloads\sicredi\sicredi\templates\Gestor\GerenciarReservas\modals.html", line 16, in top-level template code
<li><a href="{{ url_for('reservas') }}" class="flex items-center p-3 text-gray-700 rounded-lg hover:bg-gray-100"><span class="ml-3">Reserva de Equipamentos</span></a></li>
File "C:\Python312\Lib\site-packages\flask\app.py", line 1071, in url_for
return self.handle_url_build_error(error, endpoint, values)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\flask\app.py", line 1060, in url_for
rv = url_adapter.build(  # type: ignore[union-attr]
     
File "C:\Python312\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
raise BuildError(endpoint, values, method, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reservas'. Did you mean 'gestor_reservas' instead?
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.




